config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :users

  get '/auth/:provider/callback' => 'authentication#index'

  get 'game/:ID' =>'game#show'

  get 'game' => 'game#index'

  get 'about' => 'about#index'

  get 'terms' => 'about#terms'

  get '/' => 'game#index'

  get '/sign-up' => 'registrations#new', as: :signup
  post '/sign-up' => 'registrations#create'
  get '/sign-in' => 'authentication#new', as: :signin
  post '/sign-in' => 'authentication#create'
  get '/sign-out' => 'authentication#destroy', as: :signout

end

app/models/odds_feed.rb
class OddsFeed

  def initialize
  @odds = Faraday.new(:url => 'http://jsonodds.com/api/odds') do |faraday|
    faraday.request  :url_encoded
    faraday.response :logger
    faraday.adapter  Faraday.default_adapter
  end
    @odds.headers = {'JsonOdds-API-Key' => ENV["API_KEY"]}
  end

  def games(sport)
      game = @odds.get "http://jsonodds.com/api/odds/#{sport}"
      JSON.parse(game.body)
  end




end

app/models/tweet_fetcher.rb
class TweetFetcher

  def initialize
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["KEY"]
      config.consumer_secret     = ENV["SECRET_KEY"]
      config.access_token        = ENV["TOKEN"]
      config.access_token_secret = ENV["SECRET_TOKEN"]
    end
  end

  def find_tweets(word=nil)
    word ||= "barbets"
    @client.search("##{word} -rt", result_type: "recent").take(10)
  end


end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, :hometown, :birthday, presence: true

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Caching::Pages
  self.page_cache_directory = "#{Rails.root.to_s}/public/page_cache"
  
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  def authenticate
    redirect_to signin_path unless current_user
  end

  helper_method :current_user

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def index
    @name = env['omniauth.auth']
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/game_controller.rb
class GameController < ApplicationController
  caches_page :index

  def index
    @odds = OddsFeed.new
    @tweet = TweetFetcher.new
    @sorted_games = @odds.games(params[:sport])
    @team_tweets = @tweet.find_tweets(params[:word])
  end

  def show
    @odds = OddsFeed.new
    @game_show = @odds.games(params[:sport])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation))
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path, notice: 'User was successfully deleted'
  end

  def show
  end

  def edit
  end

private

  def user_params
    params.require(:user).permit(:name, :hometown, :birthday, :email, :password, :password_confirmation)
  end

  def set_task
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="container">
  <p>This is all about us</p>
</div>

app/views/authentication/index.html.erb
<%= @name['info']['name'] %>

app/views/authentication/new.html.erb
<h1>Sign In</h1>

<%= form_tag signin_path do |f| %>

<% if @sign_in_error %>
<p>
  <%= @sign_in_error %>
</p>
<% end %>

<div>
  <%= label_tag :email %>
</div>
<div>
  <%= email_field_tag :email %>
</div>

<div>
  <%= label_tag :password %>
</div>
<div>
  <%= password_field_tag :password %>
</div>

<div>
  <%= submit_tag "Sign in" %>
</div>

<% end %>

app/views/game/index.html.erb
<%= form_tag 'game', method: :get do %>
<%= label_tag 'Sport' %>
<%= text_field_tag(:sport)%>
<%= submit_tag 'Get Odds' %>
<% end %>

<% @sorted_games.each do |game| %>
  <%= link_to "game/#{game['ID']}" do %>
    <p><%= game["HomeTeam"] %> vs <%= game["AwayTeam"] %></p>
    <% end %>
  <% end %>

<%= form_tag '/', method: :get do %>
<%= label_tag 'Team Tweets' %>
<%= text_field_tag(:word) %>
<%= submit_tag 'Get Tweets' %>
<% end %>

<% @team_tweets.each do |tweet| %>
  <%= tweet.text %>
  <% end %>

app/views/game/show.html.erb
<%= @sorted_games %>

app/views/home/index.html.erb
<div class="container">

  <img alt="wordcloud" class="img-responsive center-block"<%= image_tag('background.jpg') %>

  <p>&nbsp;</p>
  <p>&nbsp;</p>

  <div class="text-center col-md-2 col-md-offset-5">
    <%= link_to 'Play Now', signup_path, class: "btn btn-warning btn-lg btn-block" %>
  </div>

  <p>&nbsp;</p>
  <p>&nbsp;</p>

  <div class="text-center col-md-2 col-md-offset-5">
    <%= link_to 'How It Works', signin_path, class: "btn btn-default btn-lg btn-block" %>
  </div>

  <p>&nbsp;</p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BarBetsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
        <img alt="logo"<%= image_tag('logo.jpg') %></a>
      </div>
       <ul class="nav nav-pills" role="navigation">
            <li><a href="users#show">Profile</a></li>
            <li><a href="game#index">Games</a></li>
       <ul class="nav nav-pills pull-right" role="navigation">
         <% if current_user %>
          <%= link_to current_user.name, current_user %>
          |
          <%= link_to "Sign Out", signout_path, class:'btn btn-default' %>
         <% else %>
          <li>
              <form class='navbar-form navbar-left' role='form'>
                <%= form_tag signin_path do |f| %>
                  <div class='form-group'>
                    <%= label_tag :email %>
                    <%= email_field_tag :email, nil, class:'form-control' %>
                    <%= label_tag :password %>
                    <%= password_field_tag :password, nil, class:'form-control' %>
                    <%= submit_tag "Sign In", class:'btn btn-default' %>
                  </div>
                <% end %>
            </form>
          </li>
           <% end %>
         </ul>
       </ul>
    </div>
  </div>



<%= yield %>


<footer>

  <div class="row">
    <div class="col-md-offset-11">
      <%= link_to "About", about_path %>
      |
      <%= link_to "Terms", terms_path %>
      |
      <%= link_to 'Twitter Login', '/auth/twitter' %>
    </div>
  </div>
</div>
</body>

</html>

app/views/users/_form.html.erb
<div class='well col-md-4 col-md-offset-4'>

  <%= form_for(@user, html: {class: 'form-horizontal'}) do |f| %>

  <div class='form-group'>
    <%= f.label :name %>
    <div>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :email %>
    <div>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :hometown %>
    <div>
      <%= f.text_field :hometown, class: 'form-control' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :birthday %>
    <div>
      <%= f.date_field :birthday, class: 'form-control' %>
    </div>
  </div>



  <div class="form-group">
    <div class='text-center'>
      <%= f.submit class: "btn btn-lg btn-warning" %>
        <br></br>
      <a class="btn btn-xs btn-default" href='/users'>Cancel</a>
    </div>
  </div>
  <% end %>


</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="page-header"><h1>Edit User</h1></div>

  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="page-header"><h1>All Users</h1></div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Hometown</th>
        <th>Birthday</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.hometown %></td>
        <td><%= user.birthday %></td>
        <td>
          <%= link_to 'Edit', edit_user_path(user), class: "btn btn-xs btn-default" %>
          <%= link_to 'Delete', user, class: "btn btn-xs btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="page-header">
    <div class="text-center">
      <h1>Wise Choice</h1>
      <h3>Fill in your stats and get started!</h3>
      </div>
  </div>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="page-header"><h1>Your Profile</h1></div>
  <dl class='dl-horizontal'>
    <dt>Name</dt><dd><%= @user.name %></dd>
    <dt>Hometown</dt><dd><%= @user.hometown %></dd>
    <dt>Birthday</dt><dd><%= @user.birthday %></dd>
    <dt>Email</dt><dd><%= @user.email %></dd>
  </dl>

</div>